language: erlang

otp_release:
  - 18.2.1
  - 18.3
  - 19.0
  - 19.1

dist: trusty

sudo: true

before_install:
  - sudo add-apt-repository -y ppa:grilo-team/travis
  - sudo apt-get update -qq
  - sudo apt-get install -y liblua5.3-dev